### ISSUE TITLE
Création de l'entité Chauffe eau

### ISSUE THREAD

**Issue by Jejebond** [ArminasTV/bsb-lan-home-assistant#3]
Bonjour,

Je propose ici de commencer le développement de l'entité pour le chauffe eau qui existe depuis Home Assistant 2023.7.

Ressources pour le développement : 
https://www.home-assistant.io/integrations/water_heater.mqtt/

Question au passage, l'actuelle entitée Switch désactive l'ECS sur le 1600 mais celà met-il en hors gel automatiquement ?

Je n'ai que très peu de connaissances, j'aiderai comme je peux en fournissant un maximum d'informations. ;)

```
############################################################
##                         MQTT  BSB LAN                  ##
############################################################
- name: "Chauffe eau"
  unique_id: "esp_bsblan_waterheater"
  device:
    name: "esp-bsblan"
    configuration_url : "http://192.168.1.200"
    identifiers: "ESP32BSBLAN"
    model: "esp32dev"
    manufacturer : "Espressif"
  modes:
    - "off"
    - "performance"
    - "eco"
  mode_state_topic: "BSB-LAN/1600"
  mode_command_topic: "BSB-LAN"
  current_temperature_topic: "BSB-LAN/8830"
  mode_command_template: "{{ value if value=="off" else "on" }}"
  temperature_state_topic: "BSB-LAN/1610"
  temperature_command_topic: "BSB-LAN/1610/set"
  min_temp: "40"
  max_temp: "65"
  temperature_unit: c
  precision: 1.0
```
